/**
 * Magics AI Image Generator - Generate high-quality AI images without watermark
 */

const axios = require('axios');
const config = require('../../config');
const fs = require('fs');
const path = require('path');

// API Configuration
const API_BASE_URL = "https://image-generator-40abkidz.vercel.app/generate";

// Store generation history for each user (last 5 images)
const userHistory = new Map();

module.exports = {
    name: 'magics',
    aliases: [],
    description: 'Generate high-quality AI images without watermark',
    usage: '.magics <prompt>',
    category: 'ai',
    ownerOnly: false,

    async execute(sock, msg, args, context) {
        const { from, sender, reply, react } = context;
        
        if (args.length === 0) {
            return reply(`🎨 *AI Image Generator*\n\n` +
                       `*Usage:*\n` +
                       `• \`${config.prefix}magics <prompt>\` - Generate image\n` +
                       `• \`${config.prefix}magics history\` - View your history\n\n` +
                       `*Examples:*\n` +
                       `• \`${config.prefix}magics a beautiful sunset over mountains\`\n` +
                       `• \`${config.prefix}magics cyberpunk city at night, neon lights\`\n\n` +
                       `*Tips:*\n` +
                       `• Be specific for better results\n` +
                       `• Use descriptive words (style, colors, mood)\n` +
                       `• Add "high quality", "detailed", "4k" for better results`);
        }
        
        // Handle history command
        if (args[0].toLowerCase() === 'history') {
            return showHistory(sock, from, sender, reply);
        }
        
        // Handle clear history
        if (args[0].toLowerCase() === 'clear') {
            userHistory.delete(sender);
            return reply(`✅ Your generation history has been cleared.`);
        }
        
        const prompt = args.join(' ');
        
        if (prompt.length < 3) {
            return reply(`❌ Please provide a longer prompt (minimum 3 characters).`);
        }
        
        if (prompt.length > 500) {
            return reply(`❌ Prompt is too long (maximum 500 characters).`);
        }
        
        await react('🎨');
        
        // Send processing message (this will stay, not get deleted)
        await reply(`🎨 *Generating AI image...*\n\n📝 *Prompt:* ${prompt}\n⏳ Please wait...`);
        
        try {
            // Encode prompt for URL
            const encodedPrompt = encodeURIComponent(prompt);
            const apiUrl = `${API_BASE_URL}?prompt=${encodedPrompt}`;
            
            console.log(`[MAGICS] Generating image for: ${prompt.substring(0, 100)}...`);
            
            // Make API request
            const response = await axios({
                method: 'GET',
                url: apiUrl,
                responseType: 'arraybuffer',
                timeout: 60000,
                maxContentLength: 10 * 1024 * 1024
            });
            
            // Check if response is an image
            const contentType = response.headers['content-type'];
            if (!contentType || !contentType.startsWith('image/')) {
                throw new Error('API did not return an image. Please try again with a different prompt.');
            }
            
            // Get image size
            const fileSizeMB = (response.data.length / (1024 * 1024)).toFixed(2);
            
            // Prepare caption
            const caption = `🎨 *AI Generated Image*\n\n` +
                           `📝 *Prompt:* ${prompt}\n` +
                           `📊 *Size:* ${fileSizeMB} MB\n\n` +
                           `> *Generated by ${config.botName}*`;
            
            // Send image directly without saving to disk
            await sock.sendMessage(from, {
                image: response.data,
                caption: caption
            }, { quoted: msg });
            
            // Save to history
            saveToHistory(sender, prompt);
            
            await react('✅');
            
        } catch (error) {
            console.error('[MAGICS] Error:', error.message);
            
            let errorMessage = `❌ *Failed to generate image*\n\n`;
            
            if (error.code === 'ECONNABORTED') {
                errorMessage += `Timeout: The API took too long to respond.\nTry again with a simpler prompt.`;
            } else if (error.response?.status === 429) {
                errorMessage += `Rate limit: Too many requests. Please wait a moment.`;
            } else if (error.response?.status === 400) {
                errorMessage += `Invalid prompt. Try a different description.`;
            } else if (error.response?.status === 500) {
                errorMessage += `Server error. Please try again later.`;
            } else {
                errorMessage += `${error.message}\n\nPlease try again with a different prompt.`;
            }
            
            await reply(errorMessage);
            await react('❌');
        }
    }
};

// Helper function to save generation history
function saveToHistory(sender, prompt) {
    if (!userHistory.has(sender)) {
        userHistory.set(sender, []);
    }
    
    const history = userHistory.get(sender);
    history.unshift({
        prompt: prompt,
        timestamp: Date.now()
    });
    
    // Keep only last 10
    while (history.length > 10) {
        history.pop();
    }
    
    userHistory.set(sender, history);
}

// Helper function to show history
async function showHistory(sock, from, sender, reply) {
    const history = userHistory.get(sender);
    
    if (!history || history.length === 0) {
        return reply(`📭 *No generation history*\n\nGenerate images using \`.magics <prompt>\` first.`);
    }
    
    let historyText = `📜 *Your Image History*\n\n`;
    
    for (let i = 0; i < Math.min(history.length, 5); i++) {
        const item = history[i];
        const date = new Date(item.timestamp).toLocaleString();
        historyText += `${i + 1}. *${item.prompt.substring(0, 60)}${item.prompt.length > 60 ? '...' : ''}*\n`;
        historyText += `   📅 ${date}\n\n`;
    }
    
    historyText += `\n💡 Use \`.magics clear\` to clear history`;
    
    await reply(historyText);
}